import { EmotionOption, PersonaOption, TextPreset, VoiceOption } from "./types";

export const PERSONAS: PersonaOption[] = [
  {
    id: "child_girl",
    label: "Little Girl (ကလေး မိန်းကလေး)",
    myanmarLabel: "ကလေး မိန်းကလေး",
    category: "child",
    gender: "female",
    ageGroup: "Child (5-8 yrs)",
    myanmarAgeGroup: "ကလေးငယ် (၅ - ၈ နှစ်)",
    description: "Cute, sweet, innocent and high-pitched little girl voice with playful giggles.",
    myanmarDescription: "ချစ်စရာကောင်းပြီး ချိုသာအပြစ်ကင်းသော ကလေးမလေး အသံထွက်ပုံစံ။",
    defaultVoice: "Kore",
    defaultEmotion: "cheerful",
    promptDirective: "Speak in the persona of a sweet, cute, innocent 6-year-old child girl (ကလေး မိန်းကလေး) with a high-pitched, playful, bright, adorable and curious voice.",
    avatarBg: "from-pink-500 to-rose-400",
    iconType: "child",
  },
  {
    id: "child_boy",
    label: "Little Boy (ကလေး ယောက်ျားလေး / Boy)",
    myanmarLabel: "ကလေး Boy (ယောက်ျားလေး)",
    category: "child",
    gender: "male",
    ageGroup: "Child (6-9 yrs)",
    myanmarAgeGroup: "ကလေးငယ် (၆ - ၉ နှစ်)",
    description: "Lively, curious, playful boy voice full of childish joy and adventure.",
    myanmarDescription: "ဆော့ကစားချင်စိတ်ပြည့်ဝပြီး တက်ကြွရွှင်လန်းသော ကလေးယောက်ျားလေး (Boy) အသံ။",
    defaultVoice: "Puck",
    defaultEmotion: "cheerful",
    promptDirective: "Speak in the persona of an energetic, playful, adventurous 7-year-old young boy (ကလေး ယောက်ျားလေး / Boy) with vibrant enthusiasm and authentic child cadence.",
    avatarBg: "from-sky-500 to-blue-400",
    iconType: "child",
  },
  {
    id: "teen_girl",
    label: "Young Girl (လူငယ် မိန်းကလေး / မိန်းခလေး)",
    myanmarLabel: "လူငယ် မိန်းခလေး",
    category: "youth",
    gender: "female",
    ageGroup: "Youth (16-22 yrs)",
    myanmarAgeGroup: "လူငယ် (၁၆ - ၂၂ နှစ်)",
    description: "Modern, bright, stylish, cheerful young woman voice with friendly vibe.",
    myanmarDescription: "ပေါ့ပါးသွက်လက်ပြီး ခေတ်ဆန်သော လူငယ်မိန်းကလေးအသံ။",
    defaultVoice: "Aoede",
    defaultEmotion: "cheerful",
    promptDirective: "Speak in the persona of a vibrant, friendly, cheerful young teenage girl (လူငယ် မိန်းခလေး) with modern, bright and natural conversational inflections.",
    avatarBg: "from-fuchsia-500 to-pink-500",
    iconType: "youth",
  },
  {
    id: "teen_boy",
    label: "Young Boy / Teen (လူငယ် ယောက်ျားလေး)",
    myanmarLabel: "လူငယ် Boy (ယောက်ျားလေး)",
    category: "youth",
    gender: "male",
    ageGroup: "Youth (17-23 yrs)",
    myanmarAgeGroup: "လူငယ် (၁၇ - ၂၃ နှစ်)",
    description: "Energetic, dynamic, casual and confident teenage boy voice.",
    myanmarDescription: "သွက်လက်တက်ကြွပြီး ပေါ့ပေါ့ပါးပါး ပြောတတ်သော လူငယ်အမျိုးသားအသံ။",
    defaultVoice: "Puck",
    defaultEmotion: "motivational",
    promptDirective: "Speak in the persona of a lively, dynamic, casual young teenage boy / youth (လူငယ် ယောက်ျားလေး) with engaging and cheerful energy.",
    avatarBg: "from-cyan-500 to-blue-600",
    iconType: "youth",
  },
  {
    id: "adult_woman",
    label: "Mature Woman (မိန်းမကြီး / လူလတ်ပိုင်း အမျိုးသမီး)",
    myanmarLabel: "မိန်းမကြီး / အမျိုးသမီး",
    category: "adult",
    gender: "female",
    ageGroup: "Adult (30-48 yrs)",
    myanmarAgeGroup: "လူလတ်ပိုင်း (၃၀ - ၄၈ နှစ်)",
    description: "Warm, poised, maternal, articulate and graceful adult woman voice.",
    myanmarDescription: "နွေးထွေးဂရုစိုက်တတ်ပြီး တည်ကြည်ယဉ်ကျေးသော မိခင်/မိန်းမကြီး အသံ။",
    defaultVoice: "Kore",
    defaultEmotion: "empathetic",
    promptDirective: "Speak in the persona of a warm, sophisticated, nurturing, articulate mature woman or mother (မိန်းမကြီး / အမေ) with steady, loving and elegant delivery.",
    avatarBg: "from-amber-500 to-orange-500",
    iconType: "adult",
  },
  {
    id: "adult_man",
    label: "Adult Man (လူလတ်ပိုင်း / Man အမျိုးသား)",
    myanmarLabel: "လူလတ်ပိုင်း Man (အမျိုးသား)",
    category: "adult",
    gender: "male",
    ageGroup: "Adult (32-50 yrs)",
    myanmarAgeGroup: "လူလတ်ပိုင်း (၃၂ - ၅၀ နှစ်)",
    description: "Deep, confident, professional gentleman voice with solid resonance.",
    myanmarDescription: "ရင့်ကျက်တည်ကြည်ပြီး ယုံကြည်မှုအပြည့်ရှိသော လူကြီး လူလတ်ပိုင်း အမျိုးသား (Man) အသံ။",
    defaultVoice: "Fenrir",
    defaultEmotion: "news",
    promptDirective: "Speak in the persona of a confident, articulate, mature adult gentleman / man (လူလတ်ပိုင်း အမျိုးသား) with rich, steady, calm and professional resonance.",
    avatarBg: "from-emerald-600 to-teal-500",
    iconType: "adult",
  },
  {
    id: "elder_woman",
    label: "Grandmother (အဘွားအို / သက်ကြီး မိန်းမကြီး)",
    myanmarLabel: "သက်ကြီး အဘွားအို",
    category: "elder",
    gender: "female",
    ageGroup: "Senior (65+ yrs)",
    myanmarAgeGroup: "သက်ကြီး (၆၅+ နှစ်)",
    description: "Loving, gentle, soft-spoken and comforting elderly grandmother voice.",
    myanmarDescription: "မေတ္တာအပြည့်ဖြင့် မြေးများကို ပုံပြင်ပြောပြသလို အေးချမ်းသော အဘွားအို အသံ။",
    defaultVoice: "Zephyr",
    defaultEmotion: "storytelling",
    promptDirective: "Speak in the persona of a loving, gentle, 70-year-old grandmother / senior elder woman (သက်ကြီး အဘွားအို / မိန်းမကြီး) with soft, nostalgic, caring and comforting tone.",
    avatarBg: "from-violet-500 to-purple-600",
    iconType: "elder",
  },
  {
    id: "elder_man",
    label: "Grandfather (အဘိုးအို / သက်ကြီး လူကြီးမင်း)",
    myanmarLabel: "သက်ကြီး အဘိုးအို (လူကြီး)",
    category: "elder",
    gender: "male",
    ageGroup: "Senior (68+ yrs)",
    myanmarAgeGroup: "သက်ကြီး (၆၈+ နှစ်)",
    description: "Wise, calm, seasoned and authoritative grandfather elder voice.",
    myanmarDescription: "အတွေ့အကြုံရင့်ကျက်ပြီး ဩဝါဒစကားမိန့်ကြားသလို လေးနက်သော အဘိုးအို (လူကြီး) အသံ။",
    defaultVoice: "Charon",
    defaultEmotion: "empathetic",
    promptDirective: "Speak in the persona of a wise, calm, gentle 72-year-old grandfather / senior elder gentleman (သက်ကြီး အဘိုးအို / လူကြီး) with deep, measured, warm and experienced pacing.",
    avatarBg: "from-indigo-600 to-slate-700",
    iconType: "elder",
  },
];

export const VOICES: VoiceOption[] = [
  {
    id: "Kore",
    name: "Kore",
    myanmarName: "ကိုရီ (အမျိုးသမီး)",
    gender: "female",
    tone: "Warm, Soothing & Clear",
    myanmarTone: "နွေးထွေးကြည်လင်သော အမျိုးသမီးအသံ",
    description: "Ideal for natural conversations, audiobooks, warm greetings, and customer guidance.",
    myanmarDescription: "ပုံမှန် စကားပြောခြင်း၊ အသံထွက်စာအုပ်များ၊ ဖော်ရွေသော နှုတ်ခွန်းဆက်စကားများအတွက် အထူးသင့်လျော်သည်။",
    avatarColor: "from-rose-500 to-amber-500",
    tag: "Most Natural Female",
  },
  {
    id: "Puck",
    name: "Puck",
    myanmarName: "ပတ်ခ် (အမျိုးသား)",
    gender: "male",
    tone: "Youthful, Energetic & Bright",
    myanmarTone: "သွက်လက်တက်ကြွသော လူငယ်အမျိုးသားအသံ",
    description: "Great for podcasts, casual discussions, tech reviews, and lively entertainment.",
    myanmarDescription: "ပေါ့တ်ကတ်စ်များ၊ နည်းပညာရှင်းပြချက်များနှင့် ပေါ့ပါးသွက်လက်သော အကြောင်းအရာများအတွက် သင့်လျော်သည်။",
    avatarColor: "from-blue-500 to-cyan-400",
    tag: "Lively Male",
  },
  {
    id: "Charon",
    name: "Charon",
    myanmarName: "ခရွန် (အမျိုးသား)",
    gender: "male",
    tone: "Deep, Authoritative & Resonant",
    myanmarTone: "ဩဇာညောင်းပြီး လေးနက်ခိုင်မာသောအသံ",
    description: "Perfect for formal news bulletins, documentaries, leadership speeches, and corporate intros.",
    myanmarDescription: "သတင်းထုတ်ပြန်ချက်များ၊ မှတ်တမ်းတင်ရုပ်ရှင်များနှင့် တရားဝင် ကြေညာချက်များအတွက် ကောင်းမွန်သည်။",
    avatarColor: "from-indigo-600 to-violet-500",
    tag: "Deep Anchor",
  },
  {
    id: "Aoede",
    name: "Aoede",
    myanmarName: "အိုဒီ (အမျိုးသမီး)",
    gender: "female",
    tone: "Melodic, Expressive & Refined",
    myanmarTone: "ချိုသာငြိမ့်ညောင်းသော သရုပ်ဆောင်အသံ",
    description: "Exceptional for dramatic storytelling, poetry recitation, emotional scenes, and brand ads.",
    myanmarDescription: "ကဗျာရွတ်ဆိုခြင်း၊ ဝတ္ထုဇာတ်လမ်းပြောပြခြင်းနှင့် ကြော်ငြာများအတွက် အလွန်ဆွဲဆောင်မှုရှိသည်။",
    avatarColor: "from-fuchsia-500 to-pink-500",
    tag: "Melodic & Expressive",
  },
  {
    id: "Fenrir",
    name: "Fenrir",
    myanmarName: "ဖန်ရာ (အမျိုးသား)",
    gender: "male",
    tone: "Crisp, Confident & Modern",
    myanmarTone: "ရှင်းလင်းပြတ်သားပြီး ယုံကြည်မှုအပြည့်ရှိသောအသံ",
    description: "Tailored for educational lectures, tutorials, product walkthroughs, and executive briefings.",
    myanmarDescription: "သင်ကြားရေးပို့ချချက်များ၊ စာသင်ခန်းရှင်းပြချက်များနှင့် လမ်းညွှန်ချက်များအတွက် အဆင်ပြေသည်။",
    avatarColor: "from-emerald-500 to-teal-400",
    tag: "Confident Instructor",
  },
  {
    id: "Zephyr",
    name: "Zephyr",
    myanmarName: "ဇက်ဖာ (ညင်သာသောအသံ)",
    gender: "neutral",
    tone: "Gentle, Breathy & Calm",
    myanmarTone: "ညင်သာအေးချမ်းသော တရားထိုင်/အိပ်ဆေးအသံ",
    description: "Engineered for guided meditations, bedtime stories, relaxed ASMR, and calming wellness scripts.",
    myanmarDescription: "စိတ်အပန်းပြေစေသော တရားထိုင်အသံ၊ ညအိပ်ရာဝင် ပုံပြင်များနှင့် အေးချမ်းသော အကြောင်းအရာများအတွက် အထူးသင့်လျော်သည်။",
    avatarColor: "from-teal-400 to-cyan-500",
    tag: "Calming & Breath",
  },
];

export const EMOTIONS: EmotionOption[] = [
  {
    id: "natural",
    label: "Natural Conversation",
    myanmarLabel: "သဘာဝ စကားပြောသံ",
    iconName: "MessageCircle",
    description: "Balanced, effortless cadence with human rhythm",
    myanmarDescription: "သာမန် လူသားတစ်ဦး စကားပြောသလို ပုံမှန်ပြေပြစ်သော အသံ",
    badgeColor: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
  },
  {
    id: "cheerful",
    label: "Cheerful & Warm",
    myanmarLabel: "ရွှင်လန်းဖော်ရွေသော အသံ",
    iconName: "Smile",
    description: "Uplifting, smiling, bright and energetic tone",
    myanmarDescription: "အပြုံးပါသော၊ နွေးထွေးဖော်ရွေပြီး စိတ်ရွှင်လန်းစေမည့် အသံ",
    badgeColor: "bg-amber-500/10 text-amber-400 border-amber-500/20",
  },
  {
    id: "storytelling",
    label: "Story Narration",
    myanmarLabel: "ပုံပြင်ပြောပြသံ",
    iconName: "BookOpen",
    description: "Expressive modulation for stories and novels",
    myanmarDescription: "နားထောင်သူကို ဆွဲဆောင်မည့် အနိမ့်အမြင့်အဆွဲအငင်ပါသော ဇာတ်လမ်းပြောသံ",
    badgeColor: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  },
  {
    id: "news",
    label: "News Broadcast",
    myanmarLabel: "သတင်းဖတ် စတိုင်",
    iconName: "Radio",
    description: "Crisp, formal, highly articulate presentation",
    myanmarDescription: "သတင်းကြေညာသူကဲ့သို့ တည်ကြည်ခိုင်မာပြီး ပြတ်သားသော အသံ",
    badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  },
  {
    id: "empathetic",
    label: "Empathetic & Caring",
    myanmarLabel: "နွေးထွေးစာနာသော အသံ",
    iconName: "Heart",
    description: "Gentle comfort, reassuring and deeply warm",
    myanmarDescription: "စိတ်သက်သာရာရစေမည့် နွေးထွေးဂရုစိုက်သော နှလုံးသားပါ အသံ",
    badgeColor: "bg-rose-500/10 text-rose-400 border-rose-500/20",
  },
  {
    id: "dramatic",
    label: "Dramatic & Intense",
    myanmarLabel: "စိတ်လှုပ်ရှားဖွယ် ဇာတ်ကောင်သံ",
    iconName: "Sparkles",
    description: "Passionate acting with deep dramatic pauses",
    myanmarDescription: "ဇာတ်ဝင်ခန်းများအတွက် စိတ်လှုပ်ရှားမှုနှင့် ရသအပြည့်ပါသော အသံ",
    badgeColor: "bg-orange-500/10 text-orange-400 border-orange-500/20",
  },
  {
    id: "motivational",
    label: "Motivational & Bold",
    myanmarLabel: "စိတ်ခွန်အားပေး အသံ",
    iconName: "Zap",
    description: "Inspiring drive, confident and empowering",
    myanmarDescription: "စိတ်ဓာတ်တက်ကြွစေပြီး ယုံကြည်မှုပေးနိုင်သော ခွန်အားပြည့် အသံ",
    badgeColor: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
  },
  {
    id: "whisper",
    label: "Soft Whisper / ASMR",
    myanmarLabel: "တိုးတိုးညင်သာ အသံ",
    iconName: "Wind",
    description: "Intimate, breathy, peaceful nighttime vibe",
    myanmarDescription: "နားထဲတိုးတိုးလေး ကပ်ပြောသလို အေးဆေးငြိမ်သက်သော အသံ",
    badgeColor: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
  },
];

export const PRESETS: TextPreset[] = [
  {
    id: "unlimited-long-story",
    category: "စာရှည် / စာကြောင်းရေ အကန့်အသတ်မရှိ",
    myanmarCategory: "စာရှည် (Unlimited Text)",
    title: "Complete Long Fairy Tale & Life Journey",
    myanmarTitle: "စာပိုဒ်ရှည် ပုံပြင်နှင့် ဘဝအတွေ့အကြုံ (Unlimited)",
    text: `ဟိုးရှေးရှေးတုန်းက သာယာလှပတဲ့ တောင်တန်းကြီးတွေရဲ့ အလယ်မှာ တိတ်ဆိတ်အေးချမ်းတဲ့ ရွာကလေးတစ်ရွာ ရှိခဲ့ပါတယ်။ ထိုရွာကလေးမှာ နေထိုင်ကြတဲ့ ရွာသူရွာသားတွေဟာ တစ်ဦးကိုတစ်ဦး အလွန်ပဲ ချစ်ခင်ကြင်နာစွာ ကူညီဖေးမလေ့ ရှိကြပါတယ်။

တစ်နေ့မှာတော့ ရွာရဲ့ ပညာရှိ အဘိုးအိုကြီးက လူငယ်မောင်မယ်တွေကို ခေါ်ယူပြီး အဖိုးတန်တဲ့ ဘဝသင်ခန်းစာတစ်ခုကို ရှင်းပြပေးခဲ့ပါတယ်။

"ငါ့မြေးတို့ရေ... လောကမှာ စိတ်ရှည်သည်းခံခြင်းနဲ့ ကြိုးစားအားထုတ်မှုဟာ အခက်အခဲမှန်သမျှကို ကျော်လွှားနိုင်တဲ့ အကောင်းဆုံးသော သော့ချက်တွေဖြစ်တယ်ကွယ်။ ဘယ်လို မုန်တိုင်းတွေပဲ တိုက်ခတ်ပါစေ၊ မိမိရဲ့ မျှော်လင့်ချက်ပန်းတိုင်ကို မလျှော့တမ်း လျှောက်လှမ်းကြပါ" လို့ အဘိုးအိုက သွန်သင်ဆုံးမခဲ့ပါတယ်။

လူငယ်တွေဟာလည်း အဘိုးအိုရဲ့ စကားကို အမြဲတမ်း နှလုံးသွင်းကာ ရွာကလေးကို ပိုမိုသာယာအောင် စည်းလုံးစွာ တည်ဆောက်ခဲ့ကြပါတော့တယ်ရှင်။`,
    recommendedVoice: "Zephyr",
    recommendedPersona: "elder_woman",
    recommendedEmotion: "storytelling",
  },
  {
    id: "child-girl-story",
    category: "ကလေး (Child)",
    myanmarCategory: "ကလေး မိန်းကလေး",
    title: "Cute Little Girl Fairy Tale",
    myanmarTitle: "ကလေးမလေး၏ ပျော်ရွှင်ဖွယ် စကားသံ",
    text: "ဟေး... မင်္ဂလာပါရှင်! သမီးကတော့ ပန်းကလေးတွေကို အရမ်းချစ်တယ်နော်... ဒီနေ့ ဥယျာဉ်ထဲမှာ လိပ်ပြာလှလှလေးတွေ ပျံသန်းနေတာ တွေ့ခဲ့ရတယ်... အရမ်းပျော်စရာကောင်းတာပဲ!",
    recommendedVoice: "Kore",
    recommendedPersona: "child_girl",
    recommendedEmotion: "cheerful",
  },
  {
    id: "child-boy-adventure",
    category: "ကလေး (Child)",
    myanmarCategory: "ကလေး Boy (ယောက်ျားလေး)",
    title: "Energetic Boy Adventure Intro",
    myanmarTitle: "ကလေး Boy ၏ စွန့်စားခန်း အသံ",
    text: "အားလုံးပဲ မင်္ဂလာပါဗျာ! ကျွန်တော်ကတော့ အာကာသယာဉ်မှူးကြီး ဖြစ်ချင်တာဗျ... မနက်ဖြန်ကျရင် သူငယ်ချင်းတွေနဲ့အတူ ဘောလုံးပွဲသွားကစားကြမယ်ဗျို့! အားလုံး အသင့်ပဲလား!",
    recommendedVoice: "Puck",
    recommendedPersona: "child_boy",
    recommendedEmotion: "cheerful",
  },
  {
    id: "teen-girl-vlog",
    category: "လူငယ် (Youth)",
    myanmarCategory: "လူငယ် မိန်းခလေး",
    title: "Trendy Young Girl Vlog Greeting",
    myanmarTitle: "လူငယ် မိန်းခလေး၏ ဖော်ရွေသော နှုတ်ခွန်းဆက်",
    text: "ဟယ်လို အားလုံးပဲ မင်္ဂလာပါရှင်... ဒီကနေ့ ဗီဒီယိုလေးမှာတော့ ကျွန်မရဲ့ နေ့စဉ်ဖြတ်သန်းမှု Lifestyle လေးတွေနဲ့အတူ အသုံးဝင်မယ့် Tips ကောင်းလေးတွေကို မျှဝေပေးသွားမှာ ဖြစ်ပါတယ်ရှင်!",
    recommendedVoice: "Aoede",
    recommendedPersona: "teen_girl",
    recommendedEmotion: "cheerful",
  },
  {
    id: "teen-boy-gaming",
    category: "လူငယ် (Youth)",
    myanmarCategory: "လူငယ် Boy (ယောက်ျားလေး)",
    title: "Youthful Boy Podcast Intro",
    myanmarTitle: "လူငယ် Boy ၏ ပေါ့တ်ကတ်စ် မိတ်ဆက်",
    text: "အားလုံးပဲ မင်္ဂလာပါဗျာ... ဒီနေ့ အစီအစဉ်မှာတော့ လူငယ်တွေကြား ရေပန်းစားနေတဲ့ နည်းပညာအသစ်တွေနဲ့ ခေတ်သစ်ဂိမ်းလောက အကြောင်းကို စိတ်ဝင်စားဖွယ် ဆွေးနွေးသွားကြပါမယ်!",
    recommendedVoice: "Puck",
    recommendedPersona: "teen_boy",
    recommendedEmotion: "motivational",
  },
  {
    id: "mature-woman-advice",
    category: "မိန်းမကြီး (Woman)",
    myanmarCategory: "မိန်းမကြီး / အမေ",
    title: "Warm Motherly Caring Advice",
    myanmarTitle: "မိန်းမကြီး / အမေ ၏ မေတ္တာပါ စကားသံ",
    text: "သမီးတို့ သားတို့ရေ... အလုပ်တွေဘယ်လောက်များများ ကိုယ့်ရဲ့ ကျန်းမာရေးကိုလည်း အထူးဂရုစိုက်ကြနော်... ထမင်းမှန်မှန်စားပြီး ရေများများသောက်ပါ... အမေတို့က အမြဲတမ်း ဆုတောင်းပေးနေပါတယ်ကွယ်။",
    recommendedVoice: "Kore",
    recommendedPersona: "adult_woman",
    recommendedEmotion: "empathetic",
  },
  {
    id: "adult-man-presentation",
    category: "လူကြီး / Man",
    myanmarCategory: "လူလတ်ပိုင်း Man (အမျိုးသား)",
    title: "Professional Business Man Speech",
    myanmarTitle: "လူကြီး Man ၏ လုပ်ငန်းခွင် ရှင်းလင်းတင်ပြချက်",
    text: "လေးစားအပ်ပါသော လူကြီးမင်းများနှင့် ဧည့်သည်တော်များခင်ဗျား... ယနေ့ ကျွန်တော်တို့ ကုမ္ပဏီမှ မိတ်ဆက်ပေးမည့် စီမံကိန်းသည် အနာဂတ် ရေရှည်ဖွံ့ဖြိုးတိုးတက်ရေးအတွက် အဓိက မှတ်တိုင်တစ်ခု ဖြစ်လာမည်ဖြစ်ပါသည်။",
    recommendedVoice: "Fenrir",
    recommendedPersona: "adult_man",
    recommendedEmotion: "news",
  },
  {
    id: "elder-grandma-story",
    category: "လူကြီး (Elder)",
    myanmarCategory: "သက်ကြီး အဘွားအို",
    title: "Grandmother's Warm Bedtime Fairy Tale",
    myanmarTitle: "အဘွားအို၏ နွေးထွေးသော ညအိပ်ပုံပြင်",
    text: "ဟိုးရှေးရှေးတုန်းကပေါ့ မြေးလေးတို့ရယ်... အဘွားတို့ ငယ်ငယ်တုန်းကဆို တောအုပ်လေးထဲမှာ ငှက်ကလေးတွေ သာယာစွာ မြည်ကြူးလေ့ရှိတယ်... အေးချမ်းတဲ့ မေတ္တာတရားတွေနဲ့ အိပ်မက်လှလှလေးတွေ မက်ပါစေကွယ်...",
    recommendedVoice: "Zephyr",
    recommendedPersona: "elder_woman",
    recommendedEmotion: "storytelling",
  },
  {
    id: "elder-grandpa-wisdom",
    category: "လူကြီး (Elder)",
    myanmarCategory: "သက်ကြီး အဘိုးအို (လူကြီး)",
    title: "Grandfather's Wise Life Advice",
    myanmarTitle: "အဘိုးအို (လူကြီး) ၏ ဩဝါဒစကား",
    text: "လူ့ဘဝဆိုတာ အမြဲတမ်း ဖြောင့်ဖြူးနေတာမဟုတ်ဘူး ငါ့မြေးတို့ရဲ့... ဘယ်လို အခက်အခဲနဲ့ ကြုံကြုံ ရိုးသားမှုနဲ့ ကြိုးစားအားထုတ်မှုကို ဘယ်တော့မှ လက်မလွှတ်ပါနဲ့... အောင်မြင်မှုဆိုတာ မုချ ရောက်လာပါလိမ့်မယ်။",
    recommendedVoice: "Charon",
    recommendedPersona: "elder_man",
    recommendedEmotion: "empathetic",
  },
  {
    id: "burmese-greeting",
    category: "နှုတ်ခွန်းဆက်",
    myanmarCategory: "ပုံမှန် နှုတ်ခွန်းဆက်",
    title: "Warm Myanmar Morning Greeting",
    myanmarTitle: "မင်္ဂလာနံနက်ခင်း ဖော်ရွေသော နှုတ်ခွန်းဆက်",
    text: "မင်္ဂလာရှိသော နံနက်ခင်းလေးဖြစ်ပါစေရှင်။ ဒီကနေ့တစ်နေ့တာလုံး စိတ်၏ချမ်းသာခြင်း၊ ကိုယ်၏ကျန်းမာခြင်းတို့နှင့် ပြည့်စုံပြီး၊ လိုရာဆန္ဒမှန်သမျှ အဆင်ပြေချောမွေ့ပါစေကြောင်း ဆုမွန်ကောင်းတောင်းပေးလိုက်ပါတယ်ရှင်။",
    recommendedVoice: "Kore",
    recommendedEmotion: "cheerful",
  },
  {
    id: "burmese-meditation",
    category: "တရားထိုင်",
    myanmarCategory: "တရားထိုင် / အပန်းဖြေ",
    title: "Calm Breathing Guided Meditation",
    myanmarTitle: "အေးချမ်းသော အသက်ရှူလေ့ကျင့်ခန်း",
    text: "မျက်လုံးလေးတွေကို ဖြည်းဖြည်းချင်း မှိတ်ထားလိုက်ပါ... ခန္ဓာကိုယ်တစ်ခုလုံးကို လျှော့ချလိုက်ပါ။ နှာခေါင်းကနေ လေနွေးနွေးလေးကို အေးအေးဆေးဆေး ရှူသွင်းလိုက်ပါ... ပြီးလျှင် ဖြည်းညင်းစွာ ပြန်လည်ထုတ်လွှတ်ပေးပါ... စိတ်ထဲက ပူပန်မှုအားလုံး ကင်းဝေးသွားပါစေ...",
    recommendedVoice: "Zephyr",
    recommendedEmotion: "whisper",
  },
];

export const PRO_TIPS_BURMESE = [
  "ကလေး၊ လူငယ်၊ မိန်းခလေး၊ Boy၊ မိန်းမကြီး၊ Man၊ လူကြီး (အဘိုး/အဘွား) စသည့် လူအသက်အရွယ် အလွှာစုံကို အလွယ်တကူ ရွေးချယ်နိုင်ပါသည်။",
  "သဘာဝကျကျ အသက်ရှူသံနှင့် အဖြတ်အတောက်ရရှိရန် စာသားများတွင် ပုဒ်ဖြတ်ပုဒ်ရပ်များဖြစ်သော '၊' (ပုဒ်ခွဲ) နှင့် '။' (ပုဒ်မ) တို့ကို မှန်ကန်စွာ ထည့်သွင်းပေးပါ။",
  "စာသားများ အသံထွက် ပိုမိုချောမွေ့စေရန် 'AI ပြုပြင်ရန် (Smart Polish)' ခလုတ်ကို နှိပ်၍ အဖြတ်အတောက်များကို အလိုအလျောက် ညှိယူနိုင်ပါသည်။",
  "စကားပြော အရှိန်အဟုန် (Speed) နှင့် လေသံခံစားချက် (Emotion) တို့ကို လိုအပ်သလို ပြောင်းလဲပြီး 100% လူသားအစစ်အသံကဲ့သို့ ဖန်တီးနိုင်ပါသည်။",
];

